//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorTester.probeAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="probeAPI.ISpaceProbe")]
    public interface ISpaceProbe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpaceProbe/GetDriveInfo", ReplyAction="http://tempuri.org/ISpaceProbe/GetDriveInfoResponse")]
        ProbeGateway.DriveSpaces[] GetDriveInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpaceProbe/GetFolderInfo", ReplyAction="http://tempuri.org/ISpaceProbe/GetFolderInfoResponse")]
        string GetFolderInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpaceProbeChannel : SensorTester.probeAPI.ISpaceProbe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpaceProbeClient : System.ServiceModel.ClientBase<SensorTester.probeAPI.ISpaceProbe>, SensorTester.probeAPI.ISpaceProbe {
        
        public SpaceProbeClient() {
        }
        
        public SpaceProbeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpaceProbeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpaceProbeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpaceProbeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProbeGateway.DriveSpaces[] GetDriveInfo() {
            return base.Channel.GetDriveInfo();
        }
        
        public string GetFolderInfo() {
            return base.Channel.GetFolderInfo();
        }
    }
}
