//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorTester.CRESapi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRESapi.ICRESapi")]
    public interface ICRESapi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRESapi/GetProcessAudit", ReplyAction="http://tempuri.org/ICRESapi/GetProcessAuditResponse")]
        System.Data.DataSet GetProcessAudit(string caseNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRESapiChannel : SensorTester.CRESapi.ICRESapi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRESapiClient : System.ServiceModel.ClientBase<SensorTester.CRESapi.ICRESapi>, SensorTester.CRESapi.ICRESapi {
        
        public CRESapiClient() {
        }
        
        public CRESapiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRESapiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRESapiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRESapiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetProcessAudit(string caseNo) {
            return base.Channel.GetProcessAudit(caseNo);
        }
    }
}
