//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorTester.cressvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cressvc.ICRESapi")]
    public interface ICRESapi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRESapi/GetProcessAudit", ReplyAction="http://tempuri.org/ICRESapi/GetProcessAuditResponse")]
        System.Data.DataTable GetProcessAudit(string caseNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRESapi/GetGARecords", ReplyAction="http://tempuri.org/ICRESapi/GetGARecordsResponse")]
        System.Data.DataTable GetGARecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRESapi/GetInterFaceFile", ReplyAction="http://tempuri.org/ICRESapi/GetInterFaceFileResponse")]
        CRESapi.interfaceFiles[] GetInterFaceFile(string caseNo, string pstatus, string ifSystem, string machineName, string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRESapiChannel : SensorTester.cressvc.ICRESapi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRESapiClient : System.ServiceModel.ClientBase<SensorTester.cressvc.ICRESapi>, SensorTester.cressvc.ICRESapi {
        
        public CRESapiClient() {
        }
        
        public CRESapiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRESapiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRESapiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRESapiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetProcessAudit(string caseNo) {
            return base.Channel.GetProcessAudit(caseNo);
        }
        
        public System.Data.DataTable GetGARecords() {
            return base.Channel.GetGARecords();
        }
        
        public CRESapi.interfaceFiles[] GetInterFaceFile(string caseNo, string pstatus, string ifSystem, string machineName, string userID) {
            return base.Channel.GetInterFaceFile(caseNo, pstatus, ifSystem, machineName, userID);
        }
    }
}
